<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Student_Mgmt</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ModelLayer\**" />
    <Compile Remove="ServiceLayer\**" />
    <EmbeddedResource Remove="ModelLayer\**" />
    <EmbeddedResource Remove="ServiceLayer\**" />
    <None Remove="ModelLayer\**" />
    <None Remove="ServiceLayer\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ModelLayer\ModelLayer.csproj" />
    <ProjectReference Include="..\ServiceLayer\ServiceLayer.csproj" />
  </ItemGroup>

</Project>
